### PR TITLE
Personal dev

### PR DESCRIPTION
**Pull request by SqlSnowCat**
Start to editing for personal portfolio

### CODE REVIEW

**Comment by bchiang7** [comment]
Hi, I don't think you meant to PR into my repo?

**Comment by SqlSnowCat** [comment]
Hi,
I'm really sorry about that! I'm new in this and I don't have practice, so
sorry! How can I repair to this?
Sorry!

Il giorno gio 3 ott 2019 alle ore 16:03 Brittany Chiang <
notifications@github.com> ha scritto:

**Comment by bchiang7** [comment]
No worries! If you forked this repo, you would the base branch of your pull request to be the `master` branch of your own repo, not this repo!

**Comment by SqlSnowCat** [comment]
Many thanks!

**Pull request closed without merging**
